"""GitHub integration: normalised issue model, the label state machine and adapters."""

from issuebot.github.adapter import GitHubAdapter
from issuebot.github.errors import ErrorCategory, GitHubError, PageCeilingError
from issuebot.github.fake import FakeGitHub
from issuebot.github.ghcli import GhCliAdapter
from issuebot.github.models import (
    WORKPAD_MARKER,
    AuthStatus,
    Comment,
    Issue,
    LabelEnsured,
    LinkedPr,
    Mergeable,
    RateLimit,
    RepoInfo,
    StateLabel,
    is_workpad_body,
)
from issuebot.github.normalise import issue_from_node, label_name, repo_short_name, role_for
from issuebot.github.runner import GhResult, GhRunner, GhRunnerLike
from issuebot.github.state import (
    ACTIVE_STATES,
    LABEL_STYLES,
    NO_FAULT_LABEL_STYLE,
    TERMINAL_STATES,
    TERMINAL_SWEEP_ROLES,
    TRANSITIONS,
    Actor,
    LabelStyle,
    carries_no_fault,
    classify_closed,
    is_active,
    is_allowed,
    is_terminal,
    model_label_style,
    next_state_for,
)
from issuebot.github.status import (
    SUMMARY_TIMEOUT_S,
    SUMMARY_URL,
    GitHubStatus,
    fetch_status_summary,
    parse_status_summary,
)

__all__ = [
    "ACTIVE_STATES",
    "LABEL_STYLES",
    "NO_FAULT_LABEL_STYLE",
    "SUMMARY_TIMEOUT_S",
    "SUMMARY_URL",
    "TERMINAL_STATES",
    "TERMINAL_SWEEP_ROLES",
    "TRANSITIONS",
    "WORKPAD_MARKER",
    "Actor",
    "AuthStatus",
    "Comment",
    "ErrorCategory",
    "FakeGitHub",
    "GhCliAdapter",
    "GhResult",
    "GhRunner",
    "GhRunnerLike",
    "GitHubAdapter",
    "GitHubError",
    "GitHubStatus",
    "Issue",
    "LabelEnsured",
    "LabelStyle",
    "LinkedPr",
    "Mergeable",
    "PageCeilingError",
    "RateLimit",
    "RepoInfo",
    "StateLabel",
    "carries_no_fault",
    "classify_closed",
    "fetch_status_summary",
    "is_active",
    "is_allowed",
    "is_terminal",
    "is_workpad_body",
    "issue_from_node",
    "label_name",
    "model_label_style",
    "next_state_for",
    "parse_status_summary",
    "repo_short_name",
    "role_for",
]
